name: house_worker
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+5

environment:
  sdk: 3.7.2

dependencies:
  cloud_firestore: 5.6.7
  cloud_functions: 5.5.0
  collection:
  cupertino_icons:
  firebase_auth: 5.5.3
  firebase_core: 3.13.0
  fl_chart: 0.71.0
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_slidable:
  freezed_annotation:
  google_fonts:
  intl:
  logging:
  package_info_plus:
  path_provider:
  riverpod:
  riverpod_annotation: 2.6.1
  share_plus:
  url_launcher:

dev_dependencies:
  build_runner:
  cider: 0.2.8
  custom_lint: 0.7.5
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: 6.9.5
  mockito:
  pedantic_mono: 1.30.3
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5

flutter:
  uses-material-design: true
